# Generated by Django 5.2.3 on 2025-06-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('send_time', models.TimeField()),
                ('channels', models.JSONField()),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
