# Generated by Django 5.2.3 on 2025-10-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
